# Generated by Django 3.2.12 on 2024-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
